/* build-tokens.mjs — DTCG JSON -> dist/tokens.css (screen) + dist/tokens.typ (print).
   ENGINE §2.3 emitter. Upgrades of 2026-07-29:
     1. tokens.typ carries typed NESTED dicts (one #let per top-level group,
        numeric steps as string keys -> `color.ground.at("100")`) alongside the
        flat `#let ds-…` bindings existing documents already import.
     2. Type-directed value transforms; oklch()-authored colours are converted
        to hex FOR PRINT at build time (lib/color.mjs owns the gamut clamp —
        Typst's own OKLCH->sRGB clamp is a known-imperfect open issue), and
        passed through untouched for CSS.
     3. --check mode: rebuild and compare against dist; any drift exits 1.
        Wire it before `typst compile` and in CI.                              */

import StyleDictionary from 'style-dictionary';
import { readdirSync, statSync, readFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseOklch, oklchToHex, oklchInSrgb } from './lib/color.mjs';

const CHECK = process.argv.includes('--check');
const root = resolve(import.meta.dirname, '..');
const brandsDir = join(root, 'brands');

/* ---------- CSS custom properties (screen: web, slides, card news) ----------
   oklch() strings pass through — every gate-relevant browser resolves them.   */

StyleDictionary.registerFormat({
  name: 'classhift/css',
  format: ({ dictionary, file }) => {
    const lines = dictionary.allTokens.map(t => {
      const raw = t.value ?? t.$value;
      const v = Array.isArray(raw) && t.$type === 'cubicBezier'
        ? `cubic-bezier(${raw.join(', ')})`
        : Array.isArray(raw)
          ? raw.map(f => (/\s/.test(f) ? `"${f}"` : f)).join(', ')
          : raw;
      return `  --ds-${t.path.join('-')}: ${v};`;
    });
    return `/* ${file.destination} — GENERATED by build:tokens. Do not edit.\n   Source: brands/${file.brand}/tokens/ */\n:root {\n${lines.join('\n')}\n}\n`;
  },
});

/* ---------- Typst (print) ----------
   px -> pt at 96dpi (x0.75), because a print point is not a CSS pixel.        */

const PX = /^(-?[\d.]+)px$/;
const EM = /^-?[\d.]+em$/;   // Typst has a native em unit, so tracking survives the crossing

/* One token value -> a Typst expression, or null when unrepresentable. */
const typstValue = t => {
  const raw = t.value ?? t.$value;
  const s = String(raw);
  if (t.$type === 'color') {
    const ok = parseOklch(s);
    if (ok) {
      if (!oklchInSrgb(ok)) console.warn(`⚠ ${t.path.join('.')}: ${s} is outside sRGB — screen (P3) and print will diverge; chroma-clamped for print`);
      return `rgb("${oklchToHex(ok)}")`;                // build owns the clamp, not Typst
    }
    if (/^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$/.test(s)) return `rgb("${s}")`; // alpha survives
    return null;
  }
  if (PX.test(s)) return `${(parseFloat(s.match(PX)[1]) * 0.75).toFixed(2)}pt`;
  if (EM.test(s)) return s;
  if (t.$type === 'fontFamily') {
    /* CSS generic family keywords mean nothing to Typst and each one costs a
       compile warning — the fallback chain crossing to print keeps real faces only. */
    const CSS_GENERIC = new Set(['system-ui', 'sans-serif', 'serif', 'monospace', 'ui-monospace', 'ui-sans-serif', 'ui-serif', 'ui-rounded', 'cursive', 'fantasy']);
    const faces = (Array.isArray(raw) ? raw : [raw]).filter(f => !CSS_GENERIC.has(f));
    return faces.length === 1 ? `"${faces[0]}"` : `(${faces.map(f => `"${f}"`).join(', ')})`;
  }
  /* fontWeight stays a number: Typst 0.15 variable fonts take it straight in
     `set text(weight: …)` — no per-weight font files, no name mapping.        */
  if (t.$type === 'number' || t.$type === 'fontWeight') return String(raw);
  if (t.$type === 'cubicBezier' && Array.isArray(raw)) return `(${raw.join(', ')})`;
  return null;                                           // duration etc. — motion does not print
};

/* Token list -> nested plain object by path, values already Typst expressions. */
const nest = tokens => {
  const tree = {};
  for (const t of tokens) {
    const v = typstValue(t);
    if (v === null) continue;
    let node = tree;
    for (const seg of t.path.slice(0, -1)) node = node[seg] ??= {};
    node[t.path.at(-1)] = v;
  }
  return tree;
};

/* Nested object -> Typst dictionary literal. Keys that are not valid Typst
   identifiers (numeric steps like "100") are emitted as string keys; access
   them with .at("100"). Single-entry dicts get the trailing comma Typst
   requires to stay a dict.                                                    */
const TYPST_KEYWORDS = new Set(['none', 'auto', 'true', 'false', 'not', 'and', 'or', 'let', 'set', 'show', 'if', 'else', 'for', 'while', 'break', 'continue', 'return', 'import', 'include', 'as', 'in', 'context']);
const isIdent = k => /^[A-Za-z_][A-Za-z0-9_-]*$/.test(k) && !TYPST_KEYWORDS.has(k);
const toTypstDict = (obj, indent = 1) => {
  const pad = '  '.repeat(indent);
  const entries = Object.entries(obj).map(([k, v]) => {
    const key = isIdent(k) ? k : `"${k}"`;
    const val = typeof v === 'object' ? toTypstDict(v, indent + 1) : v;
    return `${pad}${key}: ${val}`;
  });
  const tail = entries.length === 1 ? ',' : '';
  return `(\n${entries.join(',\n')}${tail}\n${'  '.repeat(indent - 1)})`;
};

StyleDictionary.registerFormat({
  name: 'classhift/typst',
  format: ({ dictionary, file }) => {
    /* flat bindings — the surface existing .typ documents already import */
    const flat = dictionary.allTokens.map(t => {
      const v = typstValue(t);
      return v === null
        ? `// ds-${t.path.join('-')}: ${JSON.stringify(t.value ?? t.$value)} — not representable in Typst, skipped`
        : `#let ds-${t.path.join('-')} = ${v}`;
    });
    /* nested typed dicts under ONE `ds` binding. Per-group #lets are a trap:
       a token group named `text`/`page`/`table` would shadow the Typst
       built-in of the same name the moment the file is `import *`-ed.        */
    const tree = nest(dictionary.allTokens);
    return [
      `// ${file.destination} — GENERATED by build:tokens. Do not edit.`,
      `// Source: brands/${file.brand}/tokens/ · px converted to pt at 96dpi`,
      `// oklch() values pre-converted to sRGB here (build-owned gamut clamp, ENGINE §2.3)`,
      '',
      '// ---- nested access: e.g. `ds.ground.at("100")`, `ds.sentence.size` ----',
      `#let ds = ${toTypstDict(tree)}`,
      '',
      '// ---- flat bindings (compatibility surface) ----',
      flat.join('\n'),
      '',
    ].join('\n');
  },
});

/* ---------- Astryx theme (tool-type web) ----------
   Astryx owns its own token pipeline: components read ITS variable names, set through
   defineTheme(), and there is no supported way to feed them our dist/tokens.css from
   outside. So the bridge runs the other way — we emit a defineTheme() call. Ownership
   stays at the value level (DTCG remains the source), not the pipeline level.

   Only Astryx's OWN token names go in. An earlier version also dumped every `--ds-*`
   token into the same object, which does not typecheck: `tokens` is
   `Partial<Record<TokenName, TokenValue>>`, a closed union, so the first unknown key is
   an excess-property error. The build succeeded because nothing here compiles TypeScript
   — the failure only appeared in a consuming app. The rest of the token set reaches an
   Astryx project the same way it reaches any other: by importing dist/tokens.css.       */

const ASTRYX_MAP = [
  ['--color-accent',      'action-base'],
  ['--color-background',  'surface-page'],
  ['--color-text',        'text-primary'],
  ['--color-border',      'surface-line'],
  ['--font-family-body',  'font-sans'],
  ['--font-family-code',  'font-mono'],
];

StyleDictionary.registerFormat({
  name: 'classhift/astryx',
  format: ({ dictionary, file }) => {
    const flat = new Map(dictionary.allTokens.map(t => [t.path.join('-'), t.value ?? t.$value]));
    const cssValue = raw => (Array.isArray(raw)
      ? raw.map(f => (/\s/.test(f) ? `"${f}"` : f)).join(', ')
      : String(raw));

    const mapped = ASTRYX_MAP.map(([astryxVar, ours]) => (flat.has(ours)
      ? `    '${astryxVar}': ${JSON.stringify(cssValue(flat.get(ours)))},`
      : `    // TODO ${astryxVar}: no '${ours}' role in this brand — map it by hand`));
    const missing = ASTRYX_MAP.filter(([, ours]) => !flat.has(ours)).map(([v]) => v);
    if (missing.length) console.warn(`⚠ ${file.brand}: ${missing.length} Astryx role(s) unmapped — ${missing.join(', ')}`);

    return `// ${file.destination} — GENERATED by build:tokens. Do not edit.
// Source: brands/${file.brand}/tokens/
//
// Astryx cannot read dist/tokens.css, so this file feeds it instead (ENGINE §2.2).
// Only Astryx's own token names appear here: \`tokens\` is a closed union and an
// unknown key is a TypeScript error. For everything else, import dist/tokens.css
// alongside this theme and use var(--ds-*) as normal.
//
// Regenerate after every token change, and re-check after an Astryx upgrade: the
// project is pre-1.0 and has shipped breaking theme/prop renames with codemods.
import { defineTheme } from '@astryxdesign/core/theme';

export default defineTheme({
  name: '${file.brand}',
  tokens: {
${mapped.join('\n')}
  },
});
`;
  },
});

/* ---------- build / check ---------- */

const brands = readdirSync(brandsDir).filter(b => statSync(join(brandsDir, b)).isDirectory());
let stale = [];

for (const brand of brands) {
  const dist = join(brandsDir, brand, 'dist');
  const targets = ['tokens.css', 'tokens.typ', 'astryx.theme.ts'].map(f => join(dist, f));
  const before = CHECK
    ? targets.map(p => (existsSync(p) ? readFileSync(p, 'utf8') : null))
    : [];

  const sd = new StyleDictionary({
    source: [join(brandsDir, brand, 'tokens/**/*.json').replace(/\\/g, '/')],
    log: { verbosity: 'default' },
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: `brands/${brand}/dist/`,
        files: [{ destination: 'tokens.css', format: 'classhift/css', brand }],
      },
      typst: {
        transforms: ['attribute/cti', 'name/kebab'],
        buildPath: `brands/${brand}/dist/`,
        files: [{ destination: 'tokens.typ', format: 'classhift/typst', brand }],
      },
      astryx: {
        transformGroup: 'css',
        buildPath: `brands/${brand}/dist/`,
        files: [{ destination: 'astryx.theme.ts', format: 'classhift/astryx', brand }],
      },
    },
  });
  await sd.hasInitialized;
  await sd.buildAllPlatforms();

  if (CHECK) {
    targets.forEach((p, i) => {
      const after = readFileSync(p, 'utf8');
      if (before[i] !== after) stale.push(`${brand}/${p.split(/[\\/]/).pop()}${before[i] === null ? ' (was missing)' : ''}`);
    });
  }
  console.log(`built ${brand}`);
}

if (CHECK) {
  if (stale.length) {
    console.error(`STALE — dist did not match a fresh build (now updated):\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('fresh — dist matches source');
}
